language: java
sudo: false
install: true

jdk:
- oraclejdk8

env:
- PROJECT_DIR=jaxb-missing-rootelement
- PROJECT_DIR=jaxb-unmarshal-string

script:
- cd $PROJECT_DIR
- mvn test -B
- ./runSonarQubeAnalysis.sh
